# Generated by Django 5.0 on 2023-12-19 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('logo_text', models.CharField(max_length=30)),
                ('logo_image', models.ImageField(blank=True, max_length=191, upload_to='static/img/logo/')),
                ('address', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=191, upload_to='static/img/section_image/')),
                ('about_description', models.TextField(blank=True)),
                ('about_description_end', models.TextField(blank=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='AboutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_text', models.TextField(blank=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section_content.about')),
            ],
            options={
                'verbose_name': 'About List',
                'verbose_name_plural': 'About Lis',
            },
        ),
        migrations.CreateModel(
            name='BookingFormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=191, upload_to='static/img/booking/')),
                ('note', models.TextField(blank=True)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, max_length=191, upload_to='static/img/chef/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_link', models.TextField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
            options={
                'verbose_name': 'Contact Us Page Content',
                'verbose_name_plural': 'Contact Us Page Content',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, max_length=191, upload_to='static/img/event/')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=191, upload_to='static/img/gallery/')),
                ('note', models.CharField(blank=True, max_length=250)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category_name', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(max_length=100)),
                ('menu_item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=100)),
                ('menu_item_image', models.ImageField(blank=True, max_length=191, upload_to='static/img/menu/')),
                ('menu_item_description', models.TextField(blank=True)),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section_content.menucategory')),
            ],
        ),
        migrations.CreateModel(
            name='MenuIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section_content.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(blank=True, max_length=191, upload_to='static/img/section_image/')),
                ('slider_title', models.CharField(blank=True, max_length=100)),
                ('slider_description', models.TextField(blank=True)),
                ('video_active', models.BooleanField(default=False)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('user_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('user_picture', models.ImageField(blank=True, max_length=191, upload_to='static/img/testimonial/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
            options={
                'verbose_name': 'Why Us',
                'verbose_name_plural': 'Why Us',
            },
        ),
    ]
