# Generated by Django 5.0 on 2023-12-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='closing_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
