# Generated by Django 5.0 on 2023-12-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_content', '0002_companyinformation_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='video_link',
            field=models.TextField(blank=True),
        ),
    ]
