# Generated by Django 5.0 on 2023-12-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_content', '0003_slider_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='video_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='about',
            name='video_link',
            field=models.TextField(blank=True),
        ),
    ]
