# Generated by Django 5.0 on 2023-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_content', '0004_about_video_active_about_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='category_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
