# Generated by Django 5.0 on 2023-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_content', '0005_menucategory_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='category_id',
            field=models.CharField(max_length=100),
        ),
    ]
