# Generated by Django 5.0 on 2024-01-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_content', '0008_reservation_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(default=1),
        ),
    ]
