# Generated by Django 5.0 on 2024-01-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section_content', '0009_alter_reservation_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(blank=True),
        ),
    ]
