# Generated by Django 5.0 on 2023-12-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('section_title', models.CharField(max_length=100)),
                ('section_backgroud_name', models.CharField(max_length=191)),
                ('backgroud_location', models.CharField(max_length=191)),
                ('bg_color', models.CharField(max_length=20)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_name', models.CharField(max_length=100)),
                ('active_status', models.BooleanField(default=False)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=50)),
                ('image_text', models.CharField(max_length=100)),
                ('about_description', models.TextField()),
                ('about_description_end', models.TextField()),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_content.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='site_menu',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_content.sitemenu'),
        ),
    ]
